package com.vp.constant;

public class MessageConstants {

	
	private MessageConstants(){ 
		super();
	}
	
	public static String INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR";
	public static String EMPTY_START_INDEX = "EMPTY_START_INDEX";
	public static String INVALID_START_INDEX = "INVALID_START_INDEX";
	public static String EMPTY_ROW_COUNT = "EMPTY_ROW_COUNT";
	public static String INVALID_ROW_COUNT = "INVALID_ROW_COUNT";
	public static String GET_CUSTOMER_PROFILES_SUCCESS = "GET_CUSTOMER_PROFILES_SUCCESS";
	public static String NO_CUSTOMER_PROFILES_FOUND = "NO_CUSTOMER_PROFILES_FOUND";
	public static String EMPTY_USERNAME = "EMPTY_USER_NAME";
	public static String EMPTY_NAME = "EMPTY_NAME";
	public static String EMPTY_PASSWORD = "EMPTY_PASSWORD";
	public static String EMPTY_CUSTOMER_TYPE = "EMPTY_CUSTOMER";
	public static String INVALID_CUSTOMER_TYPE = "INVALID_CUSTOMER_TYPE";
	public static String EMPTY_CUSTOMER_EMAIL = "EMPTY_CUSTOMER_EMAIL";
	public static String EMAIL_EXITS = "EMAIL_EXITS";
	public static String MOBILE_EXITS = "MOBILE_EXITS";
	public static String INVALID_CUSTOMER_EMAIL = "INVALID_CUSTOMER_EMAIL";
	public static String EMPTY_CUSTOMER_MOBILE = "EMPTY_CUSTOMER_MOBILE";
	public static String INVALID_CUSTOMER_MOBILE = "INVALID_CUSTOMER_MOBILE";
	public static String CUSTOMER_PROFILE_INSERTED_SUCCESSFULLY = "CUSTOMER_PROFILE_INSERTED_SUCCESSFULLY";
	public static String CUSTOMER_PROFILE_INSERTED_FAILURE = "CUSTOMER_PROFILE_INSERTED_FAILURE";
	public static String CUSTOMER_USERNAME_EXISTS = "CUSTOMER_USERNAME_EXISTS";
	public static String PROFILE_ALREADY_EXISTS = "PROFILE_ALREADY_EXISTS";
}

